/**
 * Every error the platform returns has a stable machine-readable code.
 * Codes are part of the API contract: renaming one is a breaking change.
 */
export const ErrorCode = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',

  // Money
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  INVALID_MONEY_AMOUNT: 'INVALID_MONEY_AMOUNT',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',

  // Database
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  DATABASE_DEADLOCK: 'DATABASE_DEADLOCK',
  UNIQUE_VIOLATION: 'UNIQUE_VIOLATION',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  CHECK_VIOLATION: 'CHECK_VIOLATION',
  SERIALIZATION_FAILURE: 'SERIALIZATION_FAILURE',

  // Idempotency
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  IDEMPOTENT_REQUEST_IN_PROGRESS: 'IDEMPOTENT_REQUEST_IN_PROGRESS',

  // Ledger
  JOURNAL_NOT_BALANCED: 'JOURNAL_NOT_BALANCED',
  JOURNAL_CURRENCY_MIXED: 'JOURNAL_CURRENCY_MIXED',
  JOURNAL_TOO_FEW_ENTRIES: 'JOURNAL_TOO_FEW_ENTRIES',
  JOURNAL_ALREADY_POSTED: 'JOURNAL_ALREADY_POSTED',
  JOURNAL_ALREADY_REVERSED: 'JOURNAL_ALREADY_REVERSED',
  LEDGER_ENTRY_IMMUTABLE: 'LEDGER_ENTRY_IMMUTABLE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_PAYMENT_STATE_TRANSITION: 'INVALID_PAYMENT_STATE_TRANSITION',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  CAPTURE_EXCEEDS_AUTHORIZED: 'CAPTURE_EXCEEDS_AUTHORIZED',
  REFUND_EXCEEDS_CAPTURED: 'REFUND_EXCEEDS_CAPTURED',
  PAYMENT_OUTCOME_UNKNOWN: 'PAYMENT_OUTCOME_UNKNOWN',
  RISK_DECLINED: 'RISK_DECLINED',

  // Provider
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_TRANSIENT_FAILURE: 'PROVIDER_TRANSIENT_FAILURE',
  PROVIDER_PERMANENT_FAILURE: 'PROVIDER_PERMANENT_FAILURE',
  PROVIDER_RESPONSE_INVALID: 'PROVIDER_RESPONSE_INVALID',

  // Merchant
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  MERCHANT_NOT_ACTIVE: 'MERCHANT_NOT_ACTIVE',

  // Settlement
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
  INVALID_SETTLEMENT_STATE_TRANSITION: 'INVALID_SETTLEMENT_STATE_TRANSITION',
  SETTLEMENT_ALREADY_CONFIRMED: 'SETTLEMENT_ALREADY_CONFIRMED',
  SETTLEMENT_EXCEEDS_PAYABLE: 'SETTLEMENT_EXCEEDS_PAYABLE',

  // Reconciliation
  DUPLICATE_STATEMENT_IMPORT: 'DUPLICATE_STATEMENT_IMPORT',
  STATEMENT_PARSE_FAILED: 'STATEMENT_PARSE_FAILED',
  RECONCILIATION_CASE_NOT_FOUND: 'RECONCILIATION_CASE_NOT_FOUND',
  INVALID_CASE_STATE_TRANSITION: 'INVALID_CASE_STATE_TRANSITION',
  RESOLUTION_REASON_REQUIRED: 'RESOLUTION_REASON_REQUIRED',

  // Messaging
  UNSUPPORTED_EVENT_VERSION: 'UNSUPPORTED_EVENT_VERSION',
  MALFORMED_EVENT: 'MALFORMED_EVENT',
  PUBLISH_FAILED: 'PUBLISH_FAILED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * How an error should be treated by retry logic (failure-model.md §2).
 * Ambiguous outcomes are deliberately non-retryable: retrying an unknown authorization
 * can create a second financial effect.
 */
export type ErrorCategory = 'TRANSIENT' | 'PERMANENT' | 'BUSINESS_CONFLICT' | 'AMBIGUOUS';
